// Generated by CoffeeScript 1.12.7
(function() {
  var http, server;

  http = require('http');

  server = require('./server.js');

  http.createServer(server.logic).listen(8888, '127.0.0.1');

}).call(this);
