// Generated by CoffeeScript 1.12.7
(function() {
  var fs, user;

  user = require('./users.js');

  fs = require('fs');

  module.exports = {
    logic: function(req, res) {
      console.log(req.url);
      if (req.url === "/save") {
        return user.save("testu", "testpwd", function() {
          return res.writeHead(200, {
            'Content-Type': 'text/plain'
          }, res.end('User is saved\n'));
        });
      } else if (req.url === "/get") {
        return user.get("testu", function() {
          return res.writeHead(200, {
            'Content-Type': 'text/plain'
          }, res.end('got the user\n'));
        });
      } else if (req.url === "/") {
        fs.readFile("public/html/index.html", function(err, html) {
          if (err) {
            throw err;
          }
        });
        return res.writeHead(200, {
          'Content-Type': 'text/plain'
        }, res.write(html), res.end);
      } else {
        res.writeHead(200, {
          'Content-Type': 'text/plain'
        });
        res.end('Route not found\n');
        return {
          port: "4444"
        };
      }
    }
  };

}).call(this);
